# Generated by Django 4.1 on 2022-10-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0005_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
