# Generated by Django 4.1 on 2022-10-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0015_checkout_products_alter_checkout_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='products',
        ),
    ]
