# Generated by Django 4.1 on 2022-10-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0016_remove_checkout_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='products',
            field=models.ManyToManyField(to='shopping_cart.order'),
        ),
    ]
